= 1.15 Additional Capabilites of the ApplicationContext
:sourcedir: ../src/main/java
:resourcedir: ../src/main/resources
:docudir: ..
:toc:
:sectnumlevels: 5


Das Interface ApplicationContext erweitert das BeanFactory Interface um zusätzliche Funktionalität in einem anwendungsoritentierten Stil bereit zu stellen.
Folgende Funktionalitäten werden hier vorgestellt.

* *Zugriff auf Messages* im i18n-Stil über die Schnittstelle MessageSource (Internalization).
* *Zugriff auf Ressourcen*, wie URLs und Dateien, über die Schnittstelle ResourceLoader.
* *Veröffentlichung von Events*, insbesondere für Beans, die die ApplicationListener-Schnittstelle implementieren, durch die Verwendung der ApplicationEventPublisher-Schnittstelle.
* *Laden mehrerer (hierarchischer) Kontexte*, die sich jeweils auf eine bestimmte Schicht konzentrieren können, z. B. die Web-Schicht einer Anwendung, über die Schnittstelle HierarchicalBeanFactory.

== 1.15.1 Internalization using MessageSource
Als Erstes müssen wir unserer Anwendung einige Sprachressourcen hinzufügen. Dazu erstellt man im resources Verzeichnis ein neues *Verzeichnis lang* und ein *Properties File link:{resourcedir}/lang/lang_en.properties[lang.properties]*.


[source,properties]
----
hello=Hello!
welcome=Welcome {0} to my tutorial
----

Oben wird "lang" als Basisname für unsere Sprachressourcen dienen.
*lang_en.properties* stellt die Standard-Ressourcendatei dar, auf die unsere Spring Boot-Anwendung zurückgreift, wenn keine Übereinstimmung gefunden wurde.

2 weitere Properties Dateien
* lang_it.properties
* lang_de.properties
werden hinzugefügt

Standardmässig entnimmt Spring  den Basisnamen einer Spring-Property namens *spring.messages.basename* oder, falls diese fehlt, versucht es, ihn aus einer Property Datei *namens messages.properties* zu entnehmen.

[source, java]
----
String basename = context.getEnvironment().getProperty("spring.messages.basename", "messages");
----

Ein Eintrag *spring.messages.basename* in der Datei link:{resourcedir}/props/application.properties[application.properties], definiert den Basisnamen für die Sprachressourcen angibt.

Einfach ausgedrückt, ermöglicht das ResourceBundle unserer Anwendung, Daten aus verschiedenen Dateien zu laden, die ortsspezifische Daten enthalten.

[source,properties]
----
spring.messages.basename=lang/lang
----

oder aber programmatisch über die link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/i18n/I18nRunner.java[I18nRunner.java] Klasse

[source, java]
----
public class I18nRunner {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
        context.refresh();

        ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
        messageSource.setBasenames("lang/lang");


        System.out.println(messageSource.getMessage("hello", null, Locale.ITALIAN));
        System.out.println(messageSource.getMessage("welcome", new Object[]{"Bruno"}, Locale.ITALIAN));

        System.out.println(messageSource.getMessage("hello", null, Locale.GERMAN));
        System.out.println(messageSource.getMessage("welcome", new Object[]{"Wolfgang"}, Locale.GERMAN));

        System.out.println(messageSource.getMessage("hello", null, Locale.ENGLISH));
        System.out.println(messageSource.getMessage("welcome", new Object[]{"Paul"}, Locale.ENGLISH));

    }
}
----
Die im obigen Beispiel verwendete ReloadableResourceBundleMessageSource Klasse gilt als Alternative zu ResourceBundleMessageSource-Klasse. Diese Variante unterstützt das gleiche Bundle-Dateiformat, ist aber flexibler als die standardmäßige JDK-basierte ResourceBundleMessageSource-Implementierung. Insbesondere ermöglicht sie das Lesen von Dateien von einem beliebigen Spring-Ressourcen-Speicherort (nicht nur vom Klassenpfad) und unterstützt das Nachladen von Bundle-Eigenschaftsdateien im laufenden Betrieb (während sie diese effizient zwischenspeichert). Siehe die Javadoc der ReloadableResourceBundleMessageSource für Details.



==== output
[source, text]
----
 Ciao!
Benvenuto Bruno al mio tutorial
Hallo!
Willkommen Wolfgang in meinem Tutorial
Hello!
Welcome Paul to my tutorial
----

[NOTE]
====
Da die MessageSource von Spring auf dem ResourceBundle von Java basiert, führt sie Bundles mit demselben Basisnamen nicht zusammen, sondern verwendet nur das erste gefundene Bundle. Nachfolgende Message-Bundles mit demselben Basisnamen werden ignoriert.
====

== 1.15.2 Standard and Custom Events
=== Warum verwenden wir Events überhaupt?
Um ein Event "abzuhören", können wir den "Listener" eines Events immer als eine weitere Methode innerhalb der Ereignisquelle schreiben, aber dadurch wird die Ereignisquelle eng an die Logik des Zuhörers gekoppelt.

Bei echten Ereignissen sind wir flexibler als bei direkten Methodenaufrufen. Wir können Listener für bestimmte Events dynamisch registrieren und deregistrieren, wie wir wollen. Wir können auch mehrere Listener für dasselbe Ereignis haben.

=== Standard Context Events
Tatsächlich gibt es in Spring eine Vielzahl von eingebauten Events, die es einem Entwickler ermöglichen, sich in den Lebenszyklus einer Anwendung und den Kontext einzuklinken und eine benutzerdefinierte Operation auszuführen.

Auch wenn wir diese Ereignisse nur selten manuell in einer Anwendung verwenden, nutzt das Framework sie intensiv in sich selbst. Beginnen wir mit der Erkundung verschiedener eingebauter Ereignisse in Spring.


.Table Spring Built-in Events
|===
|Event                  | Beschreibung

| ContextRefreshedEvent | Wenn der ApplicationContext initialisiert oder aktualisiert wird, löst Spring das ContextRefreshedEvent aus. Typischerweise kann ein Refresh mehrfach ausgelöst werden, solange der Kontext nicht geschlossen wurde.

Dieses Ereignis kann auch manuell ausgelöst werden, durch den Aufruf der Methode refresh() in der Schnittstelle ConfigurableApplicationContext aufrufen.

| ContextStartedEvent   | Durch den Aufruf der start()-Methode auf dem ConfigurableApplicationContext lösen wir dieses Ereignis aus und starten den ApplicationContext. Tatsächlich wird die Methode typischerweise verwendet, um Beans nach einem expliziten Stopp neu zu starten. Wir können die Methode auch verwenden, um Komponenten zu behandeln, die nicht für den Autostart konfiguriert sind.

Hier ist es wichtig zu beachten, dass der Aufruf von start() im Gegensatz zu refresh() immer explizit ist.

| ContextStoppedEvent   | Ein ContextStoppedEvent wird veröffentlicht, wenn der ApplicationContext gestoppt wird, indem die Methode stop() für den ConfigurableApplicationContext aufgerufen wird. Wie bereits erwähnt, können wir ein gestopptes Ereignis mit der Methode start() neu starten.

| ContextClosedEvent    | Dieses Ereignis wird veröffentlicht, wenn der ApplicationContext mit der Methode close() in ConfigurableApplicationContext geschlossen wird.
In der Realität kann ein Kontext nach dem Schließen nicht neu gestartet werden.

Ein Kontext erreicht beim Schließen sein Lebensende und kann daher nicht wie bei einem ContextStoppedEvent neu gestartet werden.

|RequestHandledEvent | Ein webspezifisches Ereignis, das allen Beans mitteilt, dass eine HTTP-Anfrage bearbeitet wurde. Dieses Ereignis wird veröffentlicht, nachdem die Anfrage abgeschlossen ist. Dieses Ereignis ist nur auf Webanwendungen anwendbar, die das DispatcherServlet von Spring verwenden.

| ServletRequestHandledEvent | Eine Unterklasse von RequestHandledEvent, die Servlet-spezifische Kontextinformationen hinzufügt.
|===

Als Beispiel ist hier auf die Klasse link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/springevents/EventListenerContainer.java[EventListenerContainer.java] verwiesen, welche aufzeigt, wie man unter Verwendung eines @EventListeners auf einer Mehthode die verschiedenen Events auslesen kann.

[source, java]
----
@Component
public class EventListenerContainer {


    @EventListener
    public void handleContextRefreshEvent(ContextRefreshedEvent ctxStartEvt) {
        System.out.println("Context Refresh Event received.");
    }

    @EventListener
    public void handleContextStartEvent(ContextStartedEvent ctxStartEvt) {
        System.out.println("Context Start Event received.");
    }

    @EventListener
    public void handleContextStopEvent(ContextStoppedEvent ctxStoppedEvt) {
        System.out.println("Context Stop Event received.");
    }

    @EventListener
    public void handleContextStopEvent(ContextClosedEvent ctxClosedEvt) {
        System.out.println("Context Closed Event received.");
    }
}
----
Siehe auch link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/springevents/SpringBuiltInEventsRunner.java[SpringBuiltInEventsRunner.java] und link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/springevents/AppConfig.java[AppConfig.java]

[source, java]
----
public class SpringBuiltInEventsRunner {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        context.start();
        context.stop();
        context.close();
    }

}
----

=== Synchrone Custom Events
Mit Spring können wir benutzerdefinierte Events/Ereignisse erstellen und veröffentlichen, die standardmäßig synchron sind. Dies hat einige Vorteile, z. B. kann der #*Listener am Transaktionskontext des Publishers teilnehmen*#. Des weiteren können unbegrenzt Ereignis-Listener registriert werden.
Weil die Event-Listener Events standardmäßig synchron empfangen, #blockiert die Methode publishEvent()#, bis alle Listener die Verarbeitung des Ereignisses abgeschlossen haben.

==== Email Versenden an whiteliste Empfänger
Am Beispiel einer Whitelist Konfiguration in einem Properties File link:{resourcedir}/props/email-config.properties[email-config.properties], werden 2 Email Adressen in eine Whitelist aufgenommen, mit dem Ziel, dass nur an diese beiden Empfänger Emails versendet werden.

[source, properties]
----
email.config.whitelist=mary@example.org,paula@example.org
----

in der link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/custom/events/synchron/service//EmailService.java[EmailService.java] Klasse wird die Whitelist über eine PropertySource (siehe link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/custom/events/synchron/EmailConfig.java[EmailConfig.java]) aus dem Property File in eine ArrayList eingelesen.
Vor dem pushen eines Events wird diese whitelist konsultiert und falls die Email-Adresse nicht in der Whitelist vorhanden, ein link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/custom/events/synchron/events/BlockedEmailEvent.java[BlockedEMailEvent],
[source, java]
----
@Getter
@Setter
public class BlockedEmailEvent extends ApplicationEvent {
    private final String emailAddress;
    private final String content;

    public BlockedEmailEvent(Object source, String emailAddress, String content) {
        super(source);
        this.emailAddress = emailAddress;
        this.content = content;
    }
}
----

andernfalls  ein link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/custom/events/synchron/events/SendEmailEvent.java[SendMailEvent]
[source, java]
----
@Getter
@Setter
public class SendEmailEvent extends ApplicationEvent {
    private final String emailAddress;
    private final String content;

    public SendEmailEvent(Object source, String emailAddress, String content) {
        super(source);
        this.emailAddress = emailAddress;
        this.content = content;
    }
}
----
ausgelöst.

[source,java]
----
@Service
public class EmailService {

    // Splitten des Property in eine ArrayList
    @Value("#{'${email.config.whitelist}'.split(',')}")
    private List<String> whitelist;
    @Autowired
    ApplicationEventPublisher publisher;

    public void sendEmail(String address, String content) {
        // wenn die Email Adresse nicht in der whitelist enthalten ist
        if (!whitelist.contains(address)) {
            publisher.publishEvent(new BlockedEmailEvent(this, address, content));
            return;
        }
        // die Email Adresse ist in der whitelist vorhanden
        publisher.publishEvent(new SendEmailEvent(this, address, content));
    }

}
----

[NOTE]
====
Anstatt den ApplicationEventPublisher mit der @Autowire Annotation zu injecten, hätte man auch von dem Interface ApplicationEventPublisherAware ableiten können. Siehe im Code Beispiel hier link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/custom/events/synchron/service/EmailServiceAware.java[EmailServiceAware.java]
====

In der Klasse link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/custom/events/synchron/listener/EmailServiceListener.java[EmailServiceListener.java] welche als Komponten gestartet wird, werden dann über die Methoden mit deren Annoation @EventListener die Events abgefangen und entsprechend reagiert

[source, java]
----
@Component
public class EmailServiceListener {

    @EventListener
    public void processBlockedEmailEvent(BlockedEmailListEvent event) {
        System.out.println("Diese EmailAdresse [" +event.getEmailAddress() +"] wurde blockiert und nicht versendet");
    }

    @EventListener
    public void processSendEmailEvent(SendEmailEvent event) {
        System.out.println("Versende Email an [" +event.getEmailAddress() +"]");
    }
}
----

[NOTE]
====
Anstelle der Annotation @EventListener auf den Methoden, könnte auch das Interface ApplicationListener implementiert werden. Siehe im Code Beispiel link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/custom/events/synchron/listener/BlockedEmailEventListener.java[BlockedEmailEventListener.java]. Allerdings braucht es hier für jeden Event einen dedizierten Listener.
====

Eine Methode kann auch auf mehrere Events hören und/oder ohne Paramter definiert werden.
[source,java]
----
@EventListener({ContextStartedEvent.class, ContextRefreshedEvent.class})
public void handleContextStart() {
    // ...
}
----

Eine link:{sourcedir}/ch/wesr/spring/core/container/annotation/additional/custom/events/synchron/EmailServiceRunner.java[EmailServiceRunner] Klasse den entsprechenden EmailService auf.


[source, java]
----
public class EmailServiceRunner {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(EmailConfig.class);

        EmailService emailService = context.getBean(EmailService.class);
        emailService.sendEmail("known.hacker@example.org", "Das ist ein Inhalt für Hacker Peter");
        emailService.sendEmail("known.spammer@example.org", "Das ist ein Inhalt für Spammer Paul");
        emailService.sendEmail("mary@example.org", "Das ist ein Inhalt für Mary");
        emailService.sendEmail("mary@xeample.org", "Das ist ein Inhalt für Mary, aber eine einem kleinen Verschreiber in der Domain Adresse");
        emailService.sendEmail("paula@example.org", "Das ist ein Inhalt für Paula");
    }
}
----

==== output
[source,text]
----
Diese EmailAdresse [known.hacker@example.org] wurde blockiert und nicht versendet
Diese EmailAdresse [known.spammer@example.org] wurde blockiert und nicht versendet
Versende Email an [mary@example.org]
Diese EmailAdresse [mary@xeample.org] wurde blockiert und nicht versendet
Versende Email an [paula@example.org]
----

Wenn eine andere Strategie für das Event-Publishing erforderlich ist, dann gibt es in der Javadoc für die Schnittstelle #ApplicationEventMulticaster# und die Implementierung ##SimpleApplicationEventMulticaste##r von Spring entsprechende Konfigurationsoptionen.

==== Filtering events with a condition

*  https://www.logicbig.com/how-to/code-snippets/jcode-spring-framework-eventlistener.html-explained/


==== Asynchrone Custom Events
!! tbd !! Überspringe ich hier

== 1.15.3 Access to low-level Resources
!! tbd !! Überspringe ich hier

== 1.15.4 Application Startup Tracking
!! tbd !! Überspringe ich hier

== 1.15.5 Application Context Instantiation
!! tbd !! Überspringe ich hier

== 1.15.6 Deployeing a Spring ApplicationContext as Java EE RAR File
!! tbd !! Überspringe ich hier

== 1.16 The Bean Factory
Da ein ApplicationContext die gesamte Funktionalität einer BeanFactory enthält, ist er im Allgemeinen einer einfachen BeanFactory vorzuziehen, außer in Szenarien, in denen eine vollständige Kontrolle über die Bean-Verarbeitung erforderlich ist.

== Referenzen
* https://lokalise.com/blog/spring-boot-internationalization/
* https://www.baeldung.com/java-resourcebundle
* https://www.baeldung.com/spring-context-events
* https://www.baeldung.com/spring-events
* https://reflectoring.io/spring-boot-application-events
*  https://www.logicbig.com/how-to/code-snippets/jcode-spring-framework-eventlistener.html-explained/

