= Spring Bean annotation based container configuration Beispiel
:sourcedir: ../src/main/java
:resourcedir: ../src/main/resources
:docudir: ..
:toc:

In der annotation-based Konfiguration von Spring Framework, gibt es die Möglichkeit eine Bean-Konfiguration in eine Komponentenklasse zu verschieben, anstatt XML für die Beschreibung der Bean-Verdrahtung zu verwenden. Dies geschieht durch die Verwendung von Annotationen für die entsprechende Klasse, Methode oder Felddeklaration.
Die Annotation Injection geschieht bevor der XML Injection. Somit überschreibt die XML Injection die Annotations-Eigenschaften.

== Das <context:annotation-config/> Element in der XML Konfiguration

Mit dem *<context:annotation-config/>* XML Element und dem dem *context* Namespace

* http://www.springframework.org/schema/context
* https://www.springframework.org/schema/context/spring-context.xsd

werden implizit folgende PostProcesserBeans registriert

* ConfigurationClassPostProcessor
* RequiredAnnotationBeanPostProcessor (deprecated)
* AutowiredAnnotationBeanPostProcessor
* CommonAnnotationBeanPostProcessor
* PersistenceAnnotationBeanPostProcessor
* EventListenerMethodProcessor


=== PostProcessors als eigenständige Beans definieren.
Wie immer kann man sich die PostProcesser Beans als individuelle Beans definieren
link:{resourcedir}/dependencies/annotation-based/autowired-annotation-bean-post-processor.xml[AutowiredAnnotationBeanPostProcessor Konfiguration Metadata]

[source, xml]
----
<!-- der PostProcessor für die Autowrire Injection -->
<bean class="org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor"/>
<!-- weitere bean definitions ab hier -->
----
Sieh das ganze Beispiel hier link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/AutowiredAnnotationBeanPostProcessorRunner.java[AutowiredAnnotationBeanPostProcessorRunner]

== Annotationen

Folgende Annotationen werde ich in diesem Abschnit beleuchten:

* @Required
* @Autowired
* @Qualifier
* JSR-250 Annotations (@Resource, @PreDestroy und @PostConstruct)

== @Required (deprecated)
`Die @Required-Annotation und der RequiredAnnotationBeanPostProcessor sind ab Spring Framework 5.1 formal deprecated, zugunsten der Verwendung von Konstruktorinjektion`

Daher keine weiteren Ausführungen zu diesem Thema an dieser Stelle.

== @Autowired
=== Ein einfaches Beispiel
==== link:{resourcedir}/dependencies/annotation-based/annotation-based.xml[Konfig Metadata]

[source,xml]
----
<?xml version = "1.0" encoding = "UTF-8"?>
<beans xmlns = "http://www.springframework.org/schema/beans"
       xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context = "http://www.springframework.org/schema/context"
       xsi:schemaLocation = "http://www.springframework.org/schema/beans
      http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
      http://www.springframework.org/schema/context
      http://www.springframework.org/schema/context/spring-context-3.0.xsd">
    <context:annotation-config/>
    <!-- bean definitions go here -->
    <bean id="springBeanExplorer" class="ch.wesr.spring.core.container.xml.annotationbased.autowired.SpringBeanExplorer"/>
    <bean id="springBean" class="ch.wesr.spring.core.container.xml.annotationbased.autowired.SpringBean"/>
</beans>
----

==== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/SpringBean.java[SpringBean]

[source,java]
----
public class SpringBean {

    private String objectName;
    private String klasse;

    public String getObjectName() {
        return objectName;
    }

    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }

    public String getKlasse() {
        return klasse;
    }

    public void setKlasse(String klasse) {
        this.klasse = klasse;
    }
}
----

==== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/SpringBeanExplorer.java[SpringBeanExplorer]
Die @Autowired Annotation steht in folgendem Beispiel auf dem Attribut. Sie könnte aber ebenso gut auf der Setter Methode sein. Persönlich bin ich an die Attribute Annnotation aus den SpringBoot Projekten gewöhnt.
[source, java]
----
public class SpringBeanExplorer {

    @Autowired
    private SpringBean springBean;

    public void explore() {
        springBean.setKlasse(springBean.getClass().getSimpleName());
        springBean.setObjectName("springBean");
        springBean.sayHello();
    }

    public SpringBean getSpringBean() {
        return springBean;
    }

    // @Autowired
    public void setSpringBean(SpringBean springBean) {
        this.springBean = springBean;
    }
}
----
Ab Spring Framework 4.3 ist eine @Autowired-Annotation auf einem Konstruktor nicht mehr notwendig oder zunächst nur einen Konstruktor definiert. Wenn jedoch mehrere Konstruktoren verfügbar sind und es keinen primären/default Konstruktor gibt, muss mindestens einer der Konstruktoren mit @Autowired annotiert werden, um dem Container mitzuteilen, welcher zu verwenden ist. Siehe die Diskussion über link:{docudir}/doc/dependencies/di/constructor_argument_resolution.md[Constructor Argument Resolution] für Details.

=== Ein @Autowired mit Collections Beispiel
In diesem Beispiel geht es darum, dass man auch Set, Map und Properties vom Typ Collections als Beans definieren und "injecten" kann.
Siehe auch das Beispiel link:{docudir}/doc/dependencies/configurations/collections.md[Collection Based Autowiring]

Damit man die Collections Elemente auch als Beans definieren kann, verwendet man z.B. den Namespace *util*.

==== link:{resourcedir}/dependencies/collections/collections.xml[Collections Configuration XML]

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:util="http://www.springframework.org/schema/util"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.springframework.org/schema/util
       http://www.springframework.org/schema/util/spring-util.xsd">

    <bean id="springBean1" class="ch.wesr.spring.core.container.xml.annotationbased.autowired.collections.SpringBean1"/>
    <bean id="springBean2" class="ch.wesr.spring.core.container.xml.annotationbased.autowired.collections.SpringBean2"/>

    <util:properties id="emails" value-type="java.lang.String" local-override="true">
        <prop key="chef">chef@firlefanz.org</prop>
        <prop key="sous-chef">sous.chef@firlefanz.org</prop>
        <prop key="sous-sous-chef">sous.sous.chef@firlefanz.org</prop>
    </util:properties>


    <util:list id="beanListe" value-type="ch.wesr.spring.core.container.xml.annotationbased.autowired.collections.MeineBean">
        <ref bean="springBean2"/>
        <ref bean="springBean1"/>
    </util:list>

    <util:map id="beanMap" map-class="java.util.HashMap" key-type="java.lang.String" value-type="ch.wesr.spring.core.container.xml.annotationbased.autowired.collections.MeineBean">
        <entry key="springBean1" value-ref="springBean1"/>
        <entry key="springBean2" value-ref="springBean2"/>
    </util:map>

    <util:set id="beanSet" value-type="ch.wesr.spring.core.container.xml.annotationbased.autowired.collections.MeineBean">
        <ref bean="springBean1"/>
        <ref bean="springBean2"/>
    </util:set>

    <bean id="collectionBean" class="ch.wesr.spring.core.container.xml.annotationbased.autowired.collections.CollectionBean">
        <property name="emails" ref="emails" />
        <property name="beanMap" ref="beanMap"/>
        <property name="beanListe" ref="beanListe"/>
        <property name="beanSet" ref="beanSet"/>
    </bean>


</beans>
----

==== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/collections/CollectionBean.java[CollectionBean.java]

[source, java]
----
 @Autowired
    private Properties emails;
    @Autowired
    private List<MeineBean> beanListe;
    @Autowired
    private HashMap<String, MeineBean> beanMap;
    @Autowired
    private Set<MeineBean> beanSet;

    @Autowired
    private SpringBean1 springBean1;

    @Autowired
    SpringBean2 springBean2;

    public void sayHello() {
        System.out.println("Emails");
        System.out.println("\tchef:           "+emails.get("chef"));
        System.out.println("\tsous-chef:      "+emails.get("sous-chef"));
        System.out.println("\tsous-sous-chef: "+emails.get("sous-sous-chef"));

        System.out.println("\n");
        System.out.println("Beanliste welche die Referenzen auf die SpringBeans* hält");
        beanListe.forEach(MeineBean::sayHello);
        System.out.println("\n");
        System.out.println("BeanMap:");
        springBean1 = (SpringBean1) beanMap.get("springBean1");
        springBean1.sayHello();
        springBean2 = (SpringBean2) beanMap.get("springBean2");
        springBean2.sayHello();

        System.out.println("\n");
        System.out.println("BeanSet: ");
        beanSet.forEach(MeineBean::sayHello);
    }
    // getter und setter
----

==== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/collections/CollectionBeanRunner.java[CollectionBeanRunner.java]

[source, java]
----
 public static void main(String[] args) {
        ConfigurableApplicationContext context = new ClassPathXmlApplicationContext("dependencies/collections/collections.xml");
        CollectionBean collectionBean = (CollectionBean) context.getBean("collectionBean");

        collectionBean.sayHello();
    }
----

==== output
[source,text]
----
Emails
    chef:           chef@firlefanz.org
    sous-chef:      sous.chef@firlefanz.org
    sous-sous-chef: sous.sous.chef@firlefanz.org


Beanliste welche die Referenzen auf die SpringBeans* hält
Hello from SpringBean2
Hello from SpringBean1


BeanMap:
Hello from SpringBean1
Hello from SpringBean2


BeanSet:
Hello from SpringBean1
Hello from SpringBean2
----

=== Fine-tuning Annotation-based Autowiring mit @Primary

Autowiring über den Typ kann zu mehreren Bean Injection Kandidaten führen. Deshalb ist es manchme notwendig, mehr Kontrolle über den Auswahlprozess zu haben. Eine Möglichkeit, dies zu erreichen, ist die @Primary-Annotation von Spring. @Primary zeigt an, dass eine bestimmte Bean bevorzugt werden soll, wenn mehrere Beans Kandidaten sind, die in einer einwertigen Abhängigkeit autowired werden sollen. Wenn es unter den Kandidaten genau eine primäre Bean gibt, wird diese zum autowired-Wert.


==== Annotation based

====== link:{resourcedir}/dependencies/autowire/annotation-primary-autowired.xml[Annotation Primary XML Config]

Beachte den *context* Namespace über welcher das Element *<context:annotation-config/>* verwendet wird.
Zudem wird in der XML Konfiguration nur die SpringBeanConfig instantiert.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
          https://www.springframework.org/schema/beans/spring-beans.xsd
          http://www.springframework.org/schema/context
          https://www.springframework.org/schema/context/spring-context.xsd">
    <context:annotation-config/>

    <bean id="configBean" class="ch.wesr.spring.core.container.xml.annotationbased.autowired.primary.SpringBeanConfig"/>
    <bean id="springBeanExplorer"
          class="ch.wesr.spring.core.container.xml.annotationbased.autowired.primary.SpringBeanExplorer"/>
</beans>
----
===== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/primary/SpringBeanConfig.java[SpringConfigBean]

Die SpringConfigBean ist einfache Klasse, welche zunächst einmal über die @Bean Annoation 2 SpringBean Instanzen erzeugt.
Somit existieren hier 2 verschiedene Kandidaten desselben Typs, welcher in der link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/primary/PrimaryAnnotationRunner.java[PrimaryAnnotationRunner.java]
injected wird.
Aufgrund dieser Konstellation wird eine Exception geworfen.

`Exception in thread "main" org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'ch.wesr.spring.core.container.xml.annotationbased.autowired.primary.SpringBean' available: expected single matching bean but found 2: primaryBean,secondaryBean
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1271)`

Erst über die *@Primary* Annotation kann Spring diese annotierte Instanz injecten.
[source,java]
----
public class SpringBeanConfig {

    // ohne @Primary -> NoUniqueBeanDefinitionException
    @Primary
    @Bean
    public SpringBean primaryBean() {
        SpringBean springBean = new SpringBean();
        springBean.setName("primary");
        return springBean;
    }

    @Bean
    public SpringBean secondaryBean() {
        SpringBean springBean = new SpringBean();
        springBean.setName("secondary");
        return springBean;
    }
}
----

====== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/primary/SpringBean.java[SpringBean.java]
Die SpringBean ist eine sehr einfache KLasse.
[source, java]
----
public class SpringBean {

    private String name;

    public void sayHello() {
        System.out.println("Hello " +name  +" from " +this.getClass().getSimpleName());
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
----

===== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/primary/SpringBeanExplorer.java[SpringBeanExplorer.java]
Die SpringBeanExplorer injected das SpringBean.
[source,java]
----
public class SpringBeanExplorer {

    @Autowired
    private SpringBean springBean;

    public void explore() {
        springBean.sayHello();
    }
}
----

====== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/primary/PrimaryAnnotationRunner.java[PrimaryAnnotationRunner.java]
Die PrimaryAnnotationRunner bekommt dann die SpringBeanExplorer Instanz und führt die explore() Methode aus.
[source,java]
----
public static void main(String[] args) {
    ApplicationContext context = new ClassPathXmlApplicationContext("dependencies/autowire/annotation-primary-autowired.xml");
    SpringBeanExplorer springBeanExplorer = (SpringBeanExplorer) context.getBean("springBeanExplorer");
    springBeanExplorer.explore();
}
----

====== output
[source, text]
----
Hello primary from SpringBean
----

===== Die xml Variante

Mit der XML Konfiguration und nur einem Namespace *beans* werden nur die beien SpringBean Instanzen beschrieben.

====== link:{resourcedir}/dependencies/autowire/primary-autowired.xml[Autowired primary="true" xml config]
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd">


    <bean id="springBean" class="ch.wesr.spring.core.container.xml.annotationbased.autowired.primary.SpringBean" primary="true">
        <property name="name" value="primary"/>
    </bean>

    <bean id="springBean2" class="ch.wesr.spring.core.container.xml.annotationbased.autowired.primary.SpringBean">
        <property name="name" value="secondary"/>
    </bean>

</beans>
----

====== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/primary/SpringBean.java[SpringBean.java]
Die SpringBean Klasse ist dieselbe wie oben.

====== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/primary/PrimaryAutowireBeanRunner.java[PrimaryAutowireBeanRunner.java]
Auch der  PrimaryAutowireBeanRunner unterscheidet sich nur im Aufruf des XML File *primary-autowired.xml*.
[source,java]
----
public static void main(String[] args) {
    ApplicationContext context = new ClassPathXmlApplicationContext("dependencies/autowire/primary-autowired.xml");
    SpringBean springBean = context.getBean(SpringBean.class);
    springBean.sayHello();
}
----

====== output
[source, text]
----
Hello primary from SpringBean
----

=== Fine-tuning Annotation-based Autowiring mit @Qualifier
Wenn man mehr Kontrolle über den Selektionsprozess über die Bean Injection haben muss, kann man Qualifier-Werte mit bestimmten Argumenten verknüpfen und so die Menge derselben Typen einschränken.


==== Annotation based

In diesem Beispiel wird die Bean Definition für die SpringBeans in der SpringBeanQualifeirConfig Klasse erstellt.

===== link:{resourcedir}/dependencies/autowire/annotation-qualifier-autowired.xml[annotation-qualifier-autowired.xml]
[source, xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
          https://www.springframework.org/schema/beans/spring-beans.xsd
          http://www.springframework.org/schema/context
          https://www.springframework.org/schema/context/spring-context.xsd">
    <context:annotation-config/>

    <bean id="configBean"
          class="ch.wesr.spring.core.container.xml.annotationbased.autowired.qualifier.SpringBeanQualifierConfig"/>
    <bean id="springBeanExplorer"
          class="ch.wesr.spring.core.container.xml.annotationbased.autowired.qualifier.SpringBeanExplorer"/>

</beans>
----
===== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/qualifier/SpringBeanQualifierConfig.java[SpringBeanQualifierConfig.java]
[source, java]
----
public class SpringBeanQualifierConfig {


    @Bean
    @Qualifier("primary")
    public SpringBean primaryBean() {
        SpringBean springBean = new SpringBean();
        springBean.setName("primary");
        return springBean;
    }

    @Bean
    @Qualifier("secondary")
    public SpringBean secondaryBean() {
        SpringBean springBean = new SpringBean();
        springBean.setName("secondary");
        return springBean;
    }
}
----
===== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/qualifier/SpringBean.java[SpringBean.java]
[source,java]
----
public class SpringBean {

    private String name;

    public void sayHello() {
        System.out.println("Hello " +name  +" from " +this.getClass().getSimpleName());
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
----

===== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/qualifier/SpringBeanExplorer.java[SpringBeanExplorer.java]
Die SpringBeanExplorer Klasse definiert, welche der beiden SpringBean sie injected haben möchte.
[source,java]
----
public class SpringBeanExplorer {

    @Autowired
    @Qualifier("primary")
    private SpringBean springBean;


    public void explore() {
        springBean.sayHello();
    }
}
----

===== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/qualifier/QualifierAnnotationRunner.java[QualifierAnnotationRunner.java]
Im Runner wird dann die SpringBeanExplorer über den ApplicationContext angefordert und die Methode expore() aufgerufen.
[source,java]
----
public static void main(String[] args) {
    ApplicationContext context = new ClassPathXmlApplicationContext("dependencies/autowire/annotation-qualifier-autowired.xml");
    SpringBeanExplorer springBeanExplorer = (SpringBeanExplorer) context.getBean("springBeanExplorer");

    springBeanExplorer.explore();
}
----
==== Die xml Variante
Aktuell bin ich mir nicht so ganz sicher, ob es gür die Qualifier Lösung auch eine reine XML Konfiguration gibt.
Die Definition der Beans wird in diesem Beispiel ausschliesslich über die XML Konfiguration erstellt.

===== link:{resourcedir}/dependencies/autowire/qualifier-autowired.xml[qualifier-autowired.xml]
[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
          https://www.springframework.org/schema/beans/spring-beans.xsd
          http://www.springframework.org/schema/context
          https://www.springframework.org/schema/context/spring-context.xsd">
    <context:annotation-config/>

    <bean class="ch.wesr.spring.core.container.xml.annotationbased.autowired.qualifier.SpringBean">
        <qualifier value="primary"/>
        <property name="name" value="primaryBean"/>
    </bean>

    <bean class="ch.wesr.spring.core.container.xml.annotationbased.autowired.qualifier.SpringBean">
        <qualifier value="secondary"/>
        <property name="name" value="secondaryBean"/>
    </bean>

    <bean id="springBeanExplorer"
          class="ch.wesr.spring.core.container.xml.annotationbased.autowired.qualifier.SpringBeanExplorer">
    </bean>

</beans>
----


===== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/qualifier/SpringBean.java[SpringBean.java]
Die SpringBean Klasse verändert sich nicht.

===== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/qualifier/SpringBeanExplorer.java[SpringBeanExplorer.java]
Auch die SpringBeanExplorer Klasse verändert sich nicht.

===== link:{sourcedir}/ch/wesr/spring/core/container/xml/annotationbased/autowired/qualifier/QualifierAutowireRunner.java[QualifierAutowireRunner.java]
Nur der Aufruf des Runners wird über das qualifier-autowired.xml anders gesteuert.
[source,java]
----
public static void main(String[] args) {
    ApplicationContext context = new ClassPathXmlApplicationContext("dependencies/autowire/qualifier-autowired.xml");
    SpringBeanExplorer springBeanExplorer =  context.getBean(SpringBeanExplorer.class);
    springBeanExplorer.explore();
}
----

== Referenzen
* https://data-flair.training/blogs/spring-annotation/[data flair - spring-annotation]
* https://www.tutorialspoint.com/spring/spring_annotation_based_configuration.htm[Tutorialspoint - Spring Annotation Based Configuration]
* https://www.netjstech.com/2016/04/autowiring-using-annotations-in-spring-autowired-inject-qualifier.html[netjstech.com - Autowiring in Spring]
* https://medium.com/@codebyamir/create-list-and-map-beans-in-spring-xml-48dce335de23[@codebyamir - Create List and Map Beans in Spring XML]
* https://www.logicbig.com/tutorials/spring-framework/spring-core/inject-bean-by-name.html[logicbig inject-bean-by-name]

link:{docudir}/spring-ioc-container.md[zurück zu spring-ioc-container]
