= Classpath Scanning und Managed Components
:sourcedir: ../src/main/java
:resourcedir: ../src/main/resources
:docudir: ..
:toc:
:sectnumlevels: 5

== 1.10.1 @Component und andere Steretyp Annotationen
Spring stellt Stereotyp Annotationen wie @Component, @Service, @Controller @Repository und weitere zur Verfügung.
Dabei ist @Component ein generischer Stereotyp für alle Spring-managed Components. So sind @Repository, @Service und @Controller eine Spezialisierung von @Component.
Hier sehr schön am Beispiel des @Repository Interface aus dem Package *org.springframework.stereotype;*
[source, java]
----
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Component
public @interface Repository {
    @AliasFor(
        annotation = Component.class
    )
    String value() default "";
}
----

Das heisst jede Klasse kann mit @Component annotiert werden. *Doch wenn man die Wahl zwischen @Component und z.B. @Service für eine Service Klasse hat, dann ist die @Service Annotation vorzuziehen*. Diese und auch die anderen von @Conmponent abgeleiteten Annotationen werden in Zukunft noch viel mehr in die Semantik von Spring einbezogen.
So unterstützt zum Beispiel die @Repository Annotation als Marker bereits die Exception Translation im Persistence Layer.

Mehr zu diesem Thema in Kapitel https://docs.spring.io/spring-framework/docs/5.3.14/reference/html/data-access.html#orm-exception-translation[Exception Translation].

== 1.10.2 Meta-Annotations und Composed Annotations

=== Was sind Meta-Annotationen?
Meta-Annotationen sind Annotationen, welche in anderen Annotationen anwendbar sind. @Component ist eine Meta-Annotation, welche in der @Repository Annotation anwendbar/verwendet ist. @Repository ist *meta-annotated* mit @Component.

=== Was sind Composed Annotations?

Unter Composed Annotations versteht man Annotationen, welche Attribute aus Meta-Annotationen neu deklarieren, um nur eine Teilmenge der möglichen Attribute aus der Meta-Annotation offen zu legen.
So wird in untenstehendem Beispiel eine SessionScope Annotation erstellt, welche den Scope hardcodiert auf *Session* festlegt, jedoch den die Anpassung des ScopedProxyMode erlaubt.

[source, java]
----
   @Target({ElementType.TYPE, ElementType.METHOD})
  @Retention(RetentionPolicy.RUNTIME)
  @Documented
  @Scope(WebApplicationContext.SCOPE_SESSION)
  public @interface SessionScope {
      /**
       * Alias for {@link Scope#proxyMode}.
       * <p>Defaults to {@link ScopedProxyMode#TARGET_CLASS}.
       */
      @AliasFor(annotation = Scope.class)
      ScopedProxyMode proxyMode() default ScopedProxyMode.TARGET_CLASS;
}
----

@SessionScope mit proxyMode
[source, java]
----
@Service
@SessionScope(proxyMode = ScopedProxyMode.INTERFACES)
public class SessionScopdeService {
    //...
}
----
@SessionScope ohne proxyMode
[source, java]
----
@Service
@SessionScope
public class SessionScopdeService {
    //...
}
----

== 1.10.3 Automatisches Erkennen von Klassen und Registrierung von Bean Definitions

Damit Spring automatisch Klassen entdecken und die zugehörigen Beans registrieren kann, braucht es eine Annotation *@ComponentScan*  mit der Angabe des *basePackage* in einer Spring Konfiguration.

Eine richtig gute Dokumentation zu diesem Thema findet man hier: https://www.logicbig.com/tutorials/spring-framework/spring-core/javaconfig-with-componnet-scan.html

=== Java Annotation @ComponentScan

[source,java]
----
@Configuration
@ComponentScan(basePackages = "ch.wesr.spring.core.container")
public class ApplicationConfig {
    // ...
}
----
Falls man mehrere verschiedene basePackages scannen will, kann man auch eine Komma-separierte Liste angeben.
[source,java]
----
@Configuration
@ComponentScan(basePackages = {"ch.wesr.spring.core.container", "ch.wesr.utils"})
public class ApplicationConfig {
    // ...
}
----

alternativ kann man auch *basePackages* weglassen
[source,java]
----
@Configuration
@ComponentScan({"ch.wesr.spring.core.container", "ch.wesr.utils"; "ch.wesr.text" "ch.wesr.monitor"})
public class ApplicationConfig {
    // ...
}
----

=== Verwende ein type-safe Attribut *usePackageClasses* in der @ComponentScan Annotation

@ComponentScan#basePackageClasses ist eine type-safe Art um ein Package für den ComponentScan zu definieren.
Dabei erstellt man ein Interface (Empfehlung von Spring), welches im zu scannenden Package liegt.

In unserem Beispiel haben wir unter dem Package/Verzeichnis src/main/java/ch/wesr/spring/core/container/annotation/basepackageclass
2 verschiedene Packages

* client
* service

in beiden Packages gibt es nun ein einfaches Interface - ein sogennantes Marker-Interface, und zwar das

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/basepackageclass/client/ClientMarkerInterface.java[ClientMarkerInterface]

[source, java]
----
public interface ClientMarkerInterface {
}
----
und das

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/basepackageclass/service/ServiceMarkerInterface.java[ServiceMarkerInterface]

[source, java]
----
public interface ServiceMarkerInterface {
}
----

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/basepackageclass/config/AppConfig.java[AppConfig.java]

Diese beiden Interfaces werden dann in der AppConfig.java über das Attribut *basePackageClasses* angegeben, welche Spring veranlasst in den Packages, wo sich diese Marker-Interfaces befinden nach weiteren Bean Definitionen zu scannen.

[source, java]
----
@Configuration
@ComponentScan(basePackageClasses = {ClientMarkerInterface.class, ServiceMarkerInterface.class})
public class AppConfig {
}
----

Die beiden Bean Definitionen *ClientBean* und *ServiceBean* sind dann mit den Spring Annotation @Component bzw. @Service gekennzeichnet.

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/basepackageclass/client/ClientBean.java[ClientBean.java]

[source, java]
----
@Component
public class ClientBean {
    public void sayHello() {
        System.out.println("Hello from " +this.getClass().getSimpleName());
    }
}
----

===== output
[source, text]
----
Hello from ClientBean
Hello from ServiceBean
----

=== XML Konfiguration für component-scann

Die Verwendung von *<context:component-scan>* aktiviert implizit die Funktionalität von *<context:annotation-config>*. Normalerweise ist es nicht notwendig, das <context:annotation-config>-Element einzuschließen, wenn <context:component-scan> verwendet wird.

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
  <beans xmlns="http://www.springframework.org/schema/beans"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:context="http://www.springframework.org/schema/context"
      xsi:schemaLocation="http://www.springframework.org/schema/beans
          https://www.springframework.org/schema/beans/spring-beans.xsd
          http://www.springframework.org/schema/context
          https://www.springframework.org/schema/context/spring-context.xsd">
      <context:component-scan base-package="org.example"/>
  </beans>
----

[CAUTION]
Auf dem Modulpfad von JDK 9 (Jigsaw) funktioniert das Scannen des Spring-Klassenpfads im Allgemeinen wie erwartet. Stellen Sie jedoch sicher, dass Ihre Komponentenklassen in Ihren Modul-Informationsdeskriptoren exportiert werden. Wenn Sie erwarten, dass Spring nicht-öffentliche Mitglieder Ihrer Klassen aufruft, stellen Sie sicher, dass diese "geöffnet" sind (d. h. dass sie eine opens-Deklaration anstelle einer exports-Deklaration in Ihrem Modul-Info-Deskriptor verwenden)

== 1.10.4. Using Filters to Customize Scanning

Standardmäßig sind Klassen, die mit

* @Component,
* @Repository,
* @Service,
* @Controller,
* @Configuration
* oder einer benutzerdefinierten Annotation, die selbst mit @Component annotiert ist,

die einzigen erkannten Kandidatenkomponenten.
Das kann man aber ändern, indem man einen benutzerdefinierten Filter verwendet. Diese Filter werden der *@ComponentScan* als Attribute mitgegeben. Jedes Filter Element erfordert ein *type* und ein *expression* Attribut

=== Folgende FilterTypen gibt es

Mit diesen Filtern könnte man noch weitere Beispiele machen, an dieser Stelle seien die möglichen Filtertypen (aus dem Enum FilterType) erwähnt.
[sourc, java]
----
package org.springframework.context.annotation;

public enum FilterType {
    ANNOTATION,
    ASSIGNABLE_TYPE,
    ASPECTJ,
    REGEX,
    CUSTOM;

    private FilterType() {
    }
}
----


.Table FilterTypes
|===
|ColumnFilter Type| Beispiel | Beschreibung
|ANNOTATION | link:#ANNOTATION[SayHelloBean.java] | Eine benutzerdefinierte Annotation
|ASSIGNABLE_TYPE | link:#ASSIGNABLE_TYPE[BenutzerDefinierterScan.java] |
|ASPECTJ | |
|REGEX | |
|CUSTOM | |
|===

=== [[ANNOTATION]]FilterType ANNOTATION

Über die MarkerInterfaces wird Spring mitgeteilt, in welchen Pfade die gewünschten Bean Defintions zu finden sind. Weil sie so einfach sind, sind sie an dieser Stelle nur verlinkt.

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/filtertype/annotation/explore/ExplorerMarkerInterface.java[ExplorerMarkerInterface.java]

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/filtertype/annotation/service/ServiceMarkerInterface.java[ServiceMarkerInterface.java]


==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/filtertype/annotation/config/AppConfig.java[AppConfig.java]

Spannender ist die AppConfig, da hier nicht nur die MarkerInterfaces definiert sind, sondern eben auch eine benuzterdefinierte Annotation -> BenutzerdefinierterScan
[source,java]
----
@Configuration
@ComponentScan(
        basePackageClasses = {ExplorerMarkerInterface.class, ServiceMarkerInterface.class},
        includeFilters = @ComponentScan.Filter(
                type = FilterType.ANNOTATION,
                classes = {BenutzerDefinierterScan.class})
)
public class AppConfig {
}
----


==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/filtertype/annotation/BenutzerDefinierterScan.java[BenutzerDefinierterScan.java]
Die BenutzerDefinierterScan Annotation wird wie folgt erstellt.

[source,java]
----
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface BenutzerDefinierterScan {
    String value() default "";
}
----

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/filtertype/annotation/service/ServiceBean.java[ServiceBean.java]

[source,java]
----
@BenutzerDefinierterScan
public class ServiceBean {
    public void sayHello() {
        System.out.println("Hello from " +this.getClass().getSimpleName());
    }
}
----

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/filtertype/annotation/AnnotationFilterTypeRunner.java[AnnotationFilterTypeRunner.java]
Der Beweis wird wie immer über den Runner Aufruf gewährleistet.

[source,java]
----
public class AnnotationFilterTypeRunner {

    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        BeanExplorer bean = context.getBean(BeanExplorer.class);
        bean.explore();
    }
}
----

==== output
[source,text]
----
Hello from ServiceBean
----

=== [[ASSIGNABLE_TYPE]]FilterType ASSIGNABLE_TYPE

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/filtertype/assignabletype/SayHelloBean.java[SayHelloBean.java]
eine einfache Klasse, ohne Spring Abhängigkeit.

[source, java]
----
public class SayHelloBean {

    public void hello() {
        System.out.println("Hello, Ich bin das SayHelloBean");
    }
}
----

Welche  in einer mit einer @Component annotierten SpringBean Klasse verwendet wird

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/filtertype/assignabletype/SpringBean.java[SpringBean.java]
----
@Component
public class SpringBean {

    @Autowired
    SayHelloBean sayHelloBean;

    public void sayHello() {
        sayHelloBean.hello();
    }
}
----
Solange die SayHelloBean nicht gescannt wird und damit dem Spring Container bekannt ist, wird eine NoSuchBeanDefinitionException geworfen.
[source, text]
----
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'ch.wesr.spring.core.container.annotation.componentscan.customscan.SayHelloBean' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
----
Damit diese Exception nicht geworfen wird, muss man dem Spring Container beibringen die SayHelloBean zu scannen, und das macht man über die Konfiguration.

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/filtertype/assignabletype/AppConfig.java[AppConfig.java]
In der AppConfig Klasse wird nicht nur das SpringBean deklariert, sondern eben auch die @ComponentScann Annotation mit einem benutzerdefinierten Filer ergänzt.

[source,java]
----
@Configuration
@ComponentScan(basePackages = "ch.wesr.spring.core.container.annotation.componentscan.customscan",
    includeFilters = @ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, classes = {SayHelloBean.class})
)
public class AppConfig {

    @Bean
    SpringBean springBean() {
        return new SpringBean();
    }

}
----

==== link:{sourcedir}/ch/wesr/spring/core/container/annotation/componentscan/filtertype/assignabletype/CustomComponentScan.java[CustomComponentScan]

[source,java]
----
public class CustomComponentScan {

    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        SpringBean bean = context.getBean(SpringBean.class);
        bean.sayHello();
    }
}
----


== Referenzen
* https://www.logicbig.com/tutorials/spring-framework/spring-core/javaconfig-with-componnet-scan.html

link:{docudir}/spring-ioc-container.md[zurück zu spring-ioc-container]


