= Environment Abstraction
:sourcedir: ../src/main/java
:resourcedir: ../src/main/resources
:docudir: ..
:toc:
:sectnumlevels: 5


Das Environment Interface ist eine in den Container integrierte Abstraktion, die zwei wichtige Aspekte der Anwendungsumgebung modelliert:

* Profile
* Properties

== 1.13.1 Bean Definition Profiles

Profile werden im Spring IoC Container verwendet umd verschiedene Bean Definitionen in verschiedenen Environments zu registrieren. Environment kann dabei verschiedene Vorstellungen hervorrufen wie

* Unterschiedliche DataSource Konfiguration für verschiedene Stages/Laufzeitstufen
* InMemory Konfigurationen wie Datenbanken oder Security
* Mandantenspezifische Konfigurationen zur Unterscheidung von Mandant A zu Mandant B Deployments
* und weitere mehr

=== @Profile

Beim Profile
link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/profile/ProfileRunner.java[ProfileRunner.java] starten wir 2 verschiedene Kontexte mit unterschiedlichen Profilen.

[source,java]
----
public class ProfileRunner {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
        context.getEnvironment().setActiveProfiles("aprofile");
        context.register(AppConfig.class);
        context.refresh();

        List<String> beans = Arrays.stream(context.getBeanDefinitionNames())
                .filter(bean -> !bean.contains("org.springframework")
                        && !bean.contains("appConfig"))
                .collect(Collectors.toList());
        Assertions.assertThat(beans)
                .hasSize(2)
                .containsExactly("AConfiguration", "springBean");

        SpringBean bean = context.getBean(SpringBean.class);
        bean.sayHello();
        context.close();


        AnnotationConfigApplicationContext contextB = new AnnotationConfigApplicationContext();
        contextB.getEnvironment().setActiveProfiles("bprofile");
        contextB.register(AppConfig.class);
        contextB.refresh();

        List<String> beansB = Arrays.stream(contextB.getBeanDefinitionNames())
                .filter(beanB -> !beanB.contains("org.springframework")
                        && !beanB.contains("appConfig"))
                .collect(Collectors.toList());
        Assertions.assertThat(beansB)
                .hasSize(2)
                .containsExactly("BConfiguration", "springBean");

        SpringBean beanB = contextB.getBean(SpringBean.class);
        beanB.sayHello();
        contextB.close();
    }
}
----

Die beiden A- und link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/profile/config/AConfiguration.java[BConfiguration.java] Klassen sind mit @Profile annotiert, hier am Beispiel der Klasse link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/profile/config/AConfiguration.java[AConfiguration.java].

[source,java]
----
@Profile("aprofile")
@Configuration
public class AConfiguration {

    @Bean
    public SpringBean springBean () {
        return new SpringBeanA();
    }
}
----

Der String im @Profile kann wie im Beispiel einen einfachen Ausdruck besitzen, oder aber einen kompliziertere Logik verwenden. Folgende Operatoren können für die ProfilAusdrücke verwendet werden.

* *!*: A logical “not” of the profile
* *&*: A logical “and” of the profiles
* *|*: A logical “or” of the profiles

[IMPORTANT]
====
Die Operatoren *&* und *|* können nicht gemischt werden, ohne Klammern zu verwenden.

Z.B. ist folgender Ausdruck nicht zulässig: "production & us-east | eu-central", sondern muss folgendermassen geschrieben werden: "production & (us-east | eu-central)"
====

[IMPORTANT]
====
Wenn eine @Configuration-Klasse mit @Profile markiert ist, werden alle @Bean-Methoden und @Import-Annotationen, die mit dieser Klasse verbunden sind, umgangen, sofern nicht eines oder mehrere der angegebenen Profile aktiv sind. Wenn eine @Komponenten- oder @Konfigurationsklasse mit @Profile({"p1", "p2"}) markiert ist, wird diese Klasse nicht registriert oder verarbeitet, es sei denn, die Profile "p1" oder "p2" wurden aktiviert. Wird einem bestimmten Profil der Operator NOT (!) vorangestellt, wird das kommentierte Element nur registriert, wenn das Profil nicht aktiv ist. Wird beispielsweise @Profile({"p1", "!p2"}) angegeben, erfolgt die Registrierung, wenn das Profil "p1" aktiv ist oder wenn das Profil "p2" nicht aktiv ist.
====
Dazu ein Beispiel:

Im Package src/main/java/ch/wesr/spring/core/container/annotation/environment/multipleprofiles gibt es folgende mit @Configuration und @Profile annotierte Klassen.

* link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/multipleprofiles/config/AConfiguration.java[AConfiguration.java] mit der @Profile({"aprofile", "!cprofile"}) Annotation
* link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/multipleprofiles/config/BConfiguration.java[BConfiguration.java] mit der @Profile({"bprofile", "!aprofile"}) Annotation
* link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/multipleprofiles/config/CConfiguration.java[CConfiguration.java] mit der @Profile({"cprofile", "!aprofile"}) Annotation



Im link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/multipleprofiles/ProfileRunner.java[ProfileRunner.java] werden 2 Profile (*aprofile* und *cprofile*) auf aktiv gesetzt.

[source,java]
----
public class ProfileRunner {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
        context.getEnvironment().setActiveProfiles("aprofile", "cprofile");

        context.register(AppConfig.class);
        context.refresh();

        List<String> beans = Arrays.stream(context.getBeanDefinitionNames())
                .filter(bean -> !bean.contains("org.springframework")
                        && !bean.contains("appConfig"))
                .collect(Collectors.toList());
        Assertions.assertThat(beans)
                .hasSize(4)
                .containsExactly("AConfiguration", "CConfiguration", "springBean", "springBeanB");

        SpringBean bean = (SpringBean) context.getBean("springBean");
        bean.sayHello();

        SpringBean beanB = (SpringBean) context.getBean("springBeanB");
        beanB.sayHello();
        context.close();
    }
}
----


==== @Profile auf Methodenebene
@Profile kann auch auf Methodenebene deklariert werden, um nur eine bestimmte Bean einer Konfigurationsklasse einzuschließen (z. B. für alternative Varianten einer bestimmten Bean), wie das folgende Beispiel zeigt:

link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/profileonmethod/ProfileRunner.java[ProfileRunner.java]

[source, java]
----
public class ProfileRunner {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
        context.getEnvironment().setActiveProfiles("aprofile", "bprofile");
        // wichtig ist, dass die activeProfiles zuerst gesetzt werden und erst dann die AppConfig.class registriert wird.
        context.register(AppConfig.class);
        context.refresh();

        List<String> beans = Arrays.stream(context.getBeanDefinitionNames())
                .filter(bean -> !bean.contains("org.springframework")
                        && !bean.contains("appConfig"))
                .collect(Collectors.toList());
        Assertions.assertThat(beans)
                .hasSize(2)
                .containsExactly("springBean", "springBeanB");

        SpringBean bean = (SpringBean) context.getBean("springBean");
        bean.sayHello();

        SpringBean beanB = (SpringBean) context.getBean("springBeanB");
        beanB.sayHello();

        context.close();
    }
}
----

In der
link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/profileonmethod/AppConfig.java[AppConfig.java] werden dann auf den Bean Methoden die Profiile definiert.

[source,java]
----
@Configuration
@ComponentScan(basePackages = {"ch.wesr.spring.core.container.annotation.environment.profileonmethod", "ch.wesr.spring.core.container.annotation.environment.beans"})
public class AppConfig {

    @Bean
    @Profile("aprofile")
    public SpringBean springBean() {
        return new SpringBeanA();
    }

    @Bean
    @Profile("bprofile")
    public SpringBean springBeanB() {
        return new SpringBeanB();
    }
}
----


==== XML Bean Defintionen für Profile

Profile können natürlich auch in der XML Konfiguration definiert werden.

In dieser sehr einfachen XML Konfiguration link:{resourcedir}/profiles/profile.xml[profile.xml] erkennt man, dass 2 Profile (zprofile, yprofile) über die *<bean/>*  Elemente definiert werden.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">


    <beans profile="zprofile">
        <bean name="springBeanA" class="ch.wesr.spring.core.container.xml.profiles.profile.beans.SpringBeanA"/>
    </beans>

    <beans profile="yprofile">
        <bean name="springBeanB" class="ch.wesr.spring.core.container.xml.profiles.profile.beans.SpringBeanB "/>
    </beans>
</beans>
----

In der link:{sourcedir}/ch/wesr/spring/core/container/xml/profiles/profile/ProfileRunner.java[ProfileRunner.java] Klasse wird dann die XML Konfiguration über den ClassPathXmlApplicationContext geladen.
Wichtig dabei ist, dass danach dem ClassPathXmlApplicationContext das Profile (zprofile) gesetzt wird.

[source,java]
----
public class ProfileRunner {

    public static void main(String[] args) {
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("profiles/profile.xml");
        context.getEnvironment().setActiveProfiles("zprofile");
        context.refresh();



        List<String> beans = Arrays.stream(context.getBeanDefinitionNames())
                .filter(bean -> !bean.contains("org.springframework")
                        && !bean.contains("appConfig"))
                .collect(Collectors.toList());
        Assertions.assertThat(beans)
                .hasSize(1)
                .containsExactly("springBeanA");

    }
}
----


== 1.13.3 @PropertySource
Die Spring-Annotation @PropertySource wird verwendet, um der Spring-Umgebung eine Eigenschaftsdatei bereitzustellen. Diese Annotation wird mit @Configuration-Klassen verwendet.

Die Spring PropertySource-Annotation ist wiederholbar, d.h. Sie können mehrere PropertySources in einer Konfigurationsklasse haben.
In der Datei link:{resourcedir}/config.properties[config.properties] sind folgende Key-Value Paare gesetzt.

[source, text]
----
springbean.name=ASpringBean
springbean.environment=Test
springbean.module=AModule
----

In der link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/propertysource/AppConfig.java[AppConfig.java] wird ersichtlich, dass es sogar möglich ist mehrere PropetySources zu definieren (mit oder ohne @PropertySources <-- beachte Mehrzahl).
Zudem kann man eine PropertySource ignorieren, wenn sie nicht gefunden wird, wie das mit dem *mich-gibt-es-nicht.properties* der Fall ist.

Die link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/propertysource/SpringBean.java[SpringBean.java] verwendet über die @Value Annotation die entsprechenden Werte aus dem config.properties Files.

[source,java]
----
@PropertySources({
        @PropertySource("classpath:config.properties"),
        @PropertySource(value = "classpath:mich-gibt-es-nicht.properties", ignoreResourceNotFound = true)
})
@Configuration
public class AppConfig {


    @Value("${springbean.name}")
    private String springbeanName;

    @Value("${springbean.environment}")
    private String springbeanEnv;

    @Value("${springbean.module}")
    private String springBeanModule;


    @Bean
    public SpringBean springBean() {

        SpringBean springBean = new SpringBean();
        springBean.setName(springbeanName);
        springBean.setEnvironment(springbeanEnv);
        springBean.setModule(springBeanModule);

        return springBean;
    }
}
----

In link:{sourcedir}/ch/wesr/spring/core/container/annotation/environment/propertysource/PropertySourceRunner.java[PropertySourceRunner.java] wird die SpringBean und die Environment Bean initialisiert.
Mit der Environment Bean werden dann die Werte aus dem config.properties verglichen.

[source,java]
----
public class PropertySourceRunner {


    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        // get Environment bean
        Environment env = (Environment) context.getBean("environment");
        // get SpringBean
        SpringBean springBean = (SpringBean) context.getBean("springBean");

        Assertions.assertThat(springBean.getName()).isEqualTo(env.getProperty("springbean.name"));
        Assertions.assertThat(springBean.getEnvironment()).isEqualTo(env.getProperty("springbean.environment"));
        Assertions.assertThat(springBean.getModule()).isEqualTo(env.getProperty("springbean.module"));

        System.out.println("hello from " +springBean.getName());
    }

}
----

Im output erkennt man die Informationsmeldung über das Property-File *mich-gibt-es-nicht.properties* was nicht gefunden wird, aber ignoriert wird - heisst keine FileNotFoundException schmeisst.

[source, text]
----
Apr. 22, 2022 10:56:26 AM org.springframework.context.annotation.ConfigurationClassParser processPropertySource
INFORMATION: Properties location [classpath:mich-gibt-es-nicht.properties] not resolvable: class path resource [mich-gibt-es-nicht.properties] cannot be opened because it does not exist
hello from ASpringBean
----
=== PropertySource Placeholder
Alle ${...}-Platzhalter, die in einer @PropertySource-Ressource vorhanden sind, werden anhand der Menge der bereits in der Umgebung registrierten Eigenschaftsquellen aufgelöst.

Folgende Beispiele zeigen auf was damit gemeint ist

[source,java]
----
// Verwenden einer Environment Variablen
@PropertySource("file:${HOME}/config.properties")
// Eine Property, die in der application.property gesetzt wird
@PropertySource("classpath:/com/${my.placeholder:default/path}/config.properties")
----


== Referenzen
* https://mkyong.com/spring/spring-profiles-example/
* https://dzone.com/articles/using-spring-profiles-xml

